# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Buch
email: davidbuch42@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 David Buch's academic website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davidbuch.github.com" # the base hostname & protocol for your site
future: true # allows future dated posts

#social networks
github_username: davidbuch
facebook_username: david.anthony.buch
linkedin_username: davidbuch-wvu18
disqus_username: null

# Build settings
markdown: kramdown

# Other Options
permalink: blog/:year/:month/:title/
excerpt_separator: "<!--more-->"